apps/common/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django.views.generic import TemplateView

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.views.i18n import javascript_catalog

from .views import ContactView, PricingView, DomainView
from accounts.views import (AccountSettingsView, MembersView, GuestsView, MemberCreateView, GuestCreateView,
                            ExportMembersPdfView, ExportMembersXlsView, AssistantCreateView)
from documents.views import RootFolderRedirectView

admin.autodiscover()
dajaxice_autodiscover()


js_info_dict = {'packages': ('common',)}

urlpatterns = patterns(
    '',
    url(r'^privacy/$', flatpage, {'url': '/privacy/'}, name='privacy'),
    url(r'^terms/$', flatpage, {'url': '/terms/'}, name='terms'),
)

urlpatterns += patterns(
    'common.views',
    url(r'^', include('registration.backends.default.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    url(r'^mEOu0wA.html$', DomainView.as_view()),

    url(r'^$', 'main', name='main'),
    url(r'^app-admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', 'accounts')),
    url(r'^accounts/email/', include('change_email.urls')),
    url(r'^billing/', include('billing.urls', 'billing')),
    url(r'^profile/', include('profiles.urls', 'profiles')),
    url(r'^contact/thankyou/', TemplateView.as_view(template_name='thankyou.html'), name='thankyou'),
    url(r'^contact/', ContactView.as_view(), name='contactus'),
    url(r'^documents/', include('documents.urls.document', 'documents')),
    url(r'^pricing/', PricingView.as_view(), name='pricing'),
    url(r'^pricing-frame/', PricingView.as_view(template_name="pricing_frame.html"), name='pricing-frame'),

    url(r'^(?P<url>[^/]+)/$', AccountSettingsView.as_view(), name='board_detail'),
    url(r'^(?P<url>[^/]+)/archives/', RootFolderRedirectView.as_view()),
    url(r'^(?P<url>[^/]+)/folders/', include('documents.urls.folder', 'folders')),
    url(r'^(?P<url>[^/]+)/committees/', include('committees.urls', 'committees')),
    url(r'^(?P<url>[^/]+)/news/', include('news.urls', 'news')),
    url(r'^(?P<url>[^/]+)/calendar/', include('boardcalendar.urls', 'calendar')),
    url(r'^(?P<url>[^/]+)/dashboard/', include('dashboard.urls', 'dashboard')),
    url(r'^(?P<url>[^/]+)/rsvp/', include('rsvp.urls', 'rsvp')),
    url(r'^(?P<url>[^/]+)/meetings/', include('meetings.urls', 'meetings')),
    url(r'^(?P<url>[^/]+)/events/', include('meetings.events_urls', 'events')),
    url(r'^(?P<url>[^/]+)/members/$', MembersView.as_view(), name='board_members'),
    url(r'^(?P<url>[^/]+)/guests/$', GuestsView.as_view(), name='board_guests'),
    url(r'^(?P<url>[^/]+)/members/create/$', MemberCreateView.as_view(), name='member_create'),
    url(r'^(?P<url>[^/]+)/guests/create/$', GuestCreateView.as_view(), name='guest_create'),
    url(r'^(?P<url>[^/]+)/assistant/(?P<pk>\d+)/create/$', AssistantCreateView.as_view(), name='assistant_create'),
    url(r'^(?P<url>[^/]+)/export/pdf/$', ExportMembersPdfView.as_view(), name='export-pdf'),
    url(r'^(?P<url>[^/]+)/export/xls/$', ExportMembersXlsView.as_view(), name='export-xls'),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/dashboard/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from .views import DashboardView, GettingStartedView, ActivitiesView


urlpatterns = patterns(
    'dashboard.views',
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^getting-started/$', GettingStartedView.as_view(), name='getting_started'),
    url(r'^activity/$', ActivitiesView.as_view(), name='activity'),
)

apps/news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from .views import NewsListView, NewsDetailView, NewsCreateView, NewsUpdateView, NewsDeleteView


urlpatterns = patterns(
    'news.views',
    url(r'^create/$', NewsCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', NewsUpdateView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)/$', NewsDeleteView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/$', NewsDetailView.as_view(), name='detail'),
    url(r'^$', NewsListView.as_view(), name='list')
)

apps/common/models.py
# -*- coding: utf-8 -*-
from django.contrib.sites.models import Site
from django.db import models
from django.template import Context
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
from django.dispatch import receiver
from django.template.loader import render_to_string, get_template_from_string
from django.conf import settings


class Feedback(models.Model):
    email = models.EmailField(_('email address'))
    message = models.TextField(_('message'))
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Feedback')
        verbose_name_plural = _('Feedbacks')

    def send_feedback(self):
        ctx_dict = {'email': self.email}
        subject = render_to_string('registration/feedback_email_subject.txt',
                                   ctx_dict)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        self.message = self.message + '\n' + Site.objects.get_current().domain
        send_mail(subject, self.message, self.email, [i[1] for i in settings.ADMINS])

    def __unicode__(self):
        return 'Feedback from {}'.format(self.email)


@receiver(models.signals.post_save, sender=Feedback)
def send_feedback_via_email(sender, created, instance, **kwargs):
    if created:
        instance.send_feedback()


class TemplateModel(models.Model):
    (ACTIVATE, RESET, MEETING, INVITE, CANCEL, TRIAL, TRIAL_IS_OVER_CANCEL,
     PAID, TRIAL_REMINDER, DOC, DOCUMENT_UPDATED, MEETING_REMINDER) = range(1, 13)

    CHOICES = (
        (ACTIVATE, _('account activation template')),
        (RESET, _('password reset template')),
        (MEETING, _('meeting invitation template')),
        (INVITE, _('member invitation template')),
        (CANCEL, _('account canceled template')),
        (TRIAL, _('trial is over template')),
        (TRIAL_IS_OVER_CANCEL, _('trial is over and account cancel template')),
        (PAID, _('paid is over template')),
        (TRIAL_REMINDER, _('trial reminder template')),
        (DOC, _('add document template')),
        (DOCUMENT_UPDATED, _('document updated template')),
        (MEETING_REMINDER, _('meeting reminder updated template'))
    )

    name = models.IntegerField(_('name'), max_length=100, choices=CHOICES, unique=True, editable=False)
    title = models.CharField(_('subject'), max_length=100)
    html = models.TextField(_('content'), help_text=_('Do not change text in braces'))

    def __unicode__(self):
        return self.get_name_display().title()

    def generate(self, content):
        content['title'] = self.title
        t = get_template_from_string(self.html)
        return t.render(Context(content))

    class Meta:
        verbose_name = _('Template editor')
        verbose_name_plural = _('Template editors')

apps/dashboard/models.py
# -*- coding: utf-8 -*-

from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.db import models
from django.utils.translation import ugettext_lazy as _

from accounts.models import Account
from common.models import TemplateModel
from documents.models import Folder


class RecentActivityManager(models.Manager):
    def for_membership(self, membership):
        queryset = self.filter(account=membership.account)
        # TODO - WEB-129
        if membership.role not in (membership.ROLES.admin, membership.ROLES.chair):
            queryset = queryset.filter(init_user=membership.user)
        return queryset


class RecentActivity(models.Model):
    """
        This will showcase the latest activity that is associated with the user.
        If he is part of a committee, and a new document is added, then this will appear here.
        Title of the activity
        (New Meetings, Updated Meetings, New Documents, Updated Documents,
        New Committee added, New Member Added
        Date of the Meeting associated to the document,
        Title of the Meeting (if a meeting).
        Location (if a meeting)
        File icon (linkable and downloadable)
        Name of file (linkable and downloadable)
        Name of who created the document
        Date of when they added it (for an audit trail)
        The six most recent activities will show up and then a pagination appears.
    """
    ADDITION, CHANGE = 1, 2
    ACTION_FLAG_CHOICES = (
        (ADDITION, 'New'),
        (CHANGE, 'Updated'),
    )

    init_user = models.ForeignKey(
        'profiles.User', related_name='recent_activity')
    account = models.ForeignKey('accounts.Account', related_name='recent_activity')
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey('content_type', 'object_id')
    action_flag = models.PositiveSmallIntegerField(
        _('action flag'), choices=ACTION_FLAG_CHOICES)
    action_time = models.DateTimeField(auto_now_add=True)

    objects = RecentActivityManager()

    class Meta:
        ordering = ['-action_time']
        verbose_name = _('Recent Activity')
        verbose_name_plural = _('Recent Activities')

    def __unicode__(self):
        return u'Recent Activity item "{}"'.format(self.content_object)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.account = Account.objects.get(pk=self.account.pk)
        super(RecentActivity, self).save(force_insert, force_update, using, update_fields)

apps/common/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.safestring import mark_safe
from .models import Feedback, TemplateModel


class ContactForm(forms.ModelForm):
    class Meta:
        model = Feedback


class RichTextWidget(forms.Textarea):
    class Media:
        css = {
            'all': ('css/kendo.common.min.css', 'css/kendo.default.min.css')
        }
        js = ('js/jquery-1.8.3.min.js', 'js/kendo.web.min.js', 'js/preview.js')

    def render(self, name, value, attrs=None):
        return mark_safe(super(RichTextWidget, self).render(name, value, attrs))


class TemplateForm(forms.ModelForm):
    class Meta:
        model = TemplateModel
        widgets = {
            'html': RichTextWidget(attrs={'class': 'kendo_editor', 'style': 'height: 500px;'})
        }

apps/common/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.views.generic import TemplateView, CreateView, View
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect

from .forms import ContactForm
from .models import Feedback
from billing.models import Plan


class MainView(TemplateView):
    template_name = 'index.html'


class ContactView(CreateView):
    model = Feedback
    template_name = 'contactus.html'
    form_class = ContactForm
    success_url = reverse_lazy('thankyou')

    def form_valid(self, form):
        form.save()
        return redirect(self.success_url)


class PricingView(TemplateView):
    template_name = 'pricing.html'

    def get_context_data(self, **kwargs):
        ctx = super(PricingView, self).get_context_data(**kwargs)
        ctx['plans'] = Plan.list_available_plans()
        ctx['show_trial_button'] = True
        return ctx


class DomainView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse('mEOu0wA')

main = MainView.as_view()

apps/dashboard/views.py
# -*- coding: utf-8 -*-
import datetime
from django.conf import settings
from django.views.generic import ListView, TemplateView
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect

from .models import RecentActivity
from accounts.models import Account
from common.mixins import LoginRequiredMixin, ActiveTabMixin, SelectBoardRequiredMixin
from committees.models import Committee
from documents.models import Document
from meetings.models import Meeting
from news.models import News
from profiles.models import Membership


class DashboardView(ActiveTabMixin, LoginRequiredMixin, SelectBoardRequiredMixin, ListView):
    context_object_name = 'meetings'
    template_name = 'dashboard/dashboard.html'
    active_tab = 'dashboard'
    paginate_by = 3

    def dispatch(self, request, *args, **kwargs):
        account = request.session.get('current_account')
        # redirect to getting started if admins first time
        if account and account.show_guide:
            membership = request.user.membership_set.get(account=account)
            if membership.is_admin and not request.session.get('has_seen_guide', False):
                return redirect('dashboard:getting_started', url=account.url)
        return super(DashboardView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(DashboardView, self).get_context_data(*args, **kwargs)
        account = self.request.session['current_account']
        membership = self.request.user.membership_set.get(account=account)
        context['account'] = account
        context['news'] = News.objects.filter(account=account, is_publish=True)[:3]
        context['activity_list'] = RecentActivity.objects.for_membership(membership)[:4]
        context['now'] = timezone.now()
        return context

    def get_queryset(self):
        membership = self.request.user.get_membership(self.request.session['current_account'])
        queryset = Meeting.objects.for_membership(membership, only_own_meetings=True)
        queryset = queryset.filter(start__gte=timezone.now())
        queryset = queryset.filter(status=Meeting.STATUSES.published)
        until_date = timezone.now() + datetime.timedelta(days=settings.DASHBOARD_MEETINGS_COUNT)
        _queryset = queryset.filter(start__lte=until_date).order_by('start')
        if len(_queryset) < 2:
            return queryset.order_by('start')[:2]
        else:
            return _queryset


class GettingStartedView(LoginRequiredMixin, SelectBoardRequiredMixin, TemplateView):
    template_name = 'dashboard/getting_started.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.GET.get('show_guide') == 'false' and 'current_account' in request.session:
            account_id = request.session['current_account'].id
            account = get_object_or_404(Account, pk=account_id)
            account.show_guide = False
            account.save(update_fields=['show_guide'])
            self.request.session['current_account'] = account
            return redirect('dashboard:dashboard', url=account.url)
        request.session['has_seen_guide'] = True
        return super(GettingStartedView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(GettingStartedView, self).get_context_data(*args, **kwargs)
        account = self.request.session['current_account']
        context['has_memberships'] = Membership.objects.filter(account=account).count() > 1
        context['has_meetings'] = Meeting.objects.filter(account=account).exists()
        context['has_documents'] = Document.objects.filter(account=account).exists()
        context['has_committees'] = Committee.objects.filter(account=account).count() > 1
        return context


class ActivitiesView(ActiveTabMixin, LoginRequiredMixin, SelectBoardRequiredMixin, ListView):
    model = RecentActivity
    context_object_name = 'recent'
    template_name = 'dashboard/activity.html'
    active_tab = 'dashboard'
    paginate_by = 6

    def get_queryset(self):
        membership = self.request.user.get_membership(self.request.session['current_account'])
        activity_list = RecentActivity.objects.for_membership(membership)
        return activity_list

apps/common/templates/dashboard/activity.html
{% extends "inner.html" %}
{% load i18n %}
{% load common_tags user_tags %}
{% block article_class %}dashboard{% endblock article_class %}

{% block workspace %}
      <h2>{{ current_membership.get_full_name }}&rsquo;s {% trans "Activities" %}</h2>
      <div class="recent-activity">
        <table>
          {% for object in recent %}
          <tr>
            <td class="cell1">{{ object.get_action_flag_display }} {{ object.content_type.name|capfirst }}:</td>

            <td class="cell2"><a href="{% if object.content_type.name == 'meeting'  %}
              {{ object.content_object.get_absolute_url }}
            {% endif %}{{ object.content_object.meeting.get_absolute_url }}">{{ object.content_object.start|date:"N j, Y" }}{{ object.content_object.meeting.start|date:"N j, Y" }}</a></td>
            <td class="cell3">
              {% if object.content_type.name == 'document' %}
                {% if object.content_object.type == object.content_object.CHARTER %}
                {% else %}
                {% trans "MEETING" %}: <a href="{{ object.content_object.meeting.get_absolute_url }}" >{{ object.content_object.meeting.name|capfirst }}</a>
                {% endif %}
                <br>
                <a class = "{{ object.content_object.extension }} custom"  href="{{ object.content_object.get_download_url }}">{{ object.content_object.filename }}</a>
              {% elif object.content_type.name == 'meeting' %}
                <a href="{{ object.content_object.get_absolute_url }}">{{ object.content_object.name|capfirst  }}</a>
                <br>
                {% trans "TIME" %}: <a href="{{ object.content_object.get_absolute_url }}">{{ object.content_object.start|date:"H:i A"}}-{{ object.content_object.end|date:"H:i A" }}</a>
                <br>
                {% trans "LOCATION" %}: <a href="{{ object.content_object.get_absolute_url }}">{{ object.content_object.location }}</a>
              {% elif object.content_type.name == 'committee' %}
                <a href="{{ object.content_object.get_absolute_url }}">{{ object.content_object.name|capfirst }}</a>
                {% if object.content_object.charter %}
                  <a class = "{{ object.content_object.charter.extension }} custom" href="{{ object.content_object.charter.get_download_url }}">{{ object.content_object.charter.name }}</a>
                {% endif %}
              {% endif %}
            </td>
            <td class="cell4">
              {% with object.init_user|membership:request.session.current_account as membership %}
                {% if object.content_type.name == 'document' %}
                  {% trans "Uploaded by " %} <a href="{{ membership.get_absolute_url }}">{{ membership.get_full_name }}</a>
                {% endif %}
                {% if object.content_type.name == 'meeting' or object.content_type.name == 'committee' %}
                  {% trans "Added by " %} <a href="{{ membership.get_absolute_url }}">{{ membership.get_full_name }}</a>
                {% endif %} on {{ object.action_time|date:"N j, Y, P" }}
              {% endwith %}
            </td>
          </tr>
          {% endfor %}
        </table>
      </div>

      {% include 'pagination.html' %}
{% endblock workspace %}

apps/common/templates/dashboard/dashboard.html
{% extends "inner.html" %}
{% load i18n common_tags user_tags permissions_tags %}
{% block article_class %}dashboard{% endblock article_class %}

{% block extra_js %}
  {{ super }}
  <script src="{{ STATIC_URL }}js/rsvp_ajax.js"></script>
{% endblock %}

{% block workspace %}
  <h2>{{ current_membership.get_full_name }}&rsquo;s {% trans "Dashboard" %}</h2>
  <div class="dashboard-meetings">
    <h2 class="upcoming-meetings">{% trans "UPCOMING MEETINGS AND EVENTS" %}</h2>
    {% if meetings %}
      {% for meeting in meetings %}
        <div class="dashboard-meeting-card">
          <div class="meeting-icon {% if meeting.is_event %}event-icon{% endif %}">
            <div class="month">{{ meeting.start|date:"N" }}</div>
            <div class="day">{{ meeting.start|date:"j" }}</div>
          </div>
          <div class="meeting-description">
            <h2>{{ meeting.name }}</h2>
            <p>{{ meeting.start|date:"l, N j, Y" }}</p>
            <p>{{ meeting.start|date:"g:i a" }} &ndash; {{ meeting.end|date:"g:i a" }}</p>
            <p>{{ meeting.get_committee_name }}</p>
            <p>{{ meeting.location }}</p>
            <a href="{{ meeting.get_absolute_url }}" class="btn meeting-btn">
              {% if meeting.is_event %}{% trans 'View Full Event Details' %}{% else %}{% trans 'View Full Meeting Details' %}{% endif %} <i></i>
            </a>
          </div>
          {% include 'rsvp/includes/meeting.html' %}
        </div>
      {% endfor %}
      {% include 'pagination.html' %}
    {% else %}
      {% trans 'No upcoming meetings scheduled.' %}
    {% endif %}
  </div>
  <div class="right-side">
    <div class="dashboard-activities">
      {% if activity_list %}
        <h2 class="upcoming-meetings"><a href="{% acc_url 'dashboard:activity' %}">{% trans "ACTIVITIES" %}</a></h2>
        {% regroup activity_list by action_time|date:"b j, Y"|capfirst as activities %}
        {% for activity in activities %}
          <div class="activities-block activities-date-block">
            <div class="point date-point"></div>
            <div class="date-title activities-object">{{ activity.grouper }}
            {% if activity.grouper == now|date:"N j, Y" %}
              <div class="today">{% trans "today" %}</div>
            {% endif %}
            </div>
          </div>
          {% for object in activity.list %}
            <div class="activities-block">
              <div class="point"></div>
              {% include 'dashboard/includes/activity.html' %}
            </div>
          {% endfor %}
        {% endfor %}
      {% endif %}
    </div>
    {% if current_membership|has_role_permission:'news.news:view' %}
      <div class="dashboard-news">
        <h2 class="upcoming-meetings">{% trans "NEWS" %}</h2>
        {% for article in news %}
          <div class="news">
            <div class="date">
              <div class="month">
                {{ article.created_at|date:"N" }}
              </div>
              <b>{{ article.created_at|date:"j" }}</b>
            </div>
            <div class="news-text">
              <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
              <i>{{ article.text|striptags|slice:"80" }} ...</i>
            </div>
          </div>
        {% endfor %}
        <div class="all-news"><a href="{% acc_url "news:list" %}">{% trans "See All News" %} &#62;</a></div>
      </div>
    {% endif %}
  </div>
{% endblock workspace %}

apps/common/templates/dashboard/getting_started.html
{% extends "inner.html" %}
{% load i18n static common_tags user_tags %}

{% block article_class %}dashboard{% endblock article_class %}
{% block extra_css %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/getting_started.css' %}">
{% endblock extra_css %}

{% block extra_js %}
  <script src="{% static 'js/kendo.web.min.js' %}"></script>
  <script src="{% static 'js/getting_started.js' %}"></script>
{% endblock extra_js %}

{% block workspace %}
<div class="getting-started">
  <div class="header text-center">
    <h2>Hurray!</h2>
    <h2>Let's get started, {{ current_membership.get_full_name }}!</h2>
    <p>Board Director is a simple tool to help you manage {{ request.session.current_account.name }}'s documents, meetings, committees, <br/>and its Board of Directors. It's easy to set up and use. Here's a few steps to get you started.</p>
  </div>
  <div class="steps text-center {% if has_memberships %}finished{% endif %}">
    <h3>Step 1: Add Board Members.</h3>
    <p>Start by adding your first Board Members. Once you've configured the roster and you're<br/>ready for everyone to sign in, you'll need to invite them.</p>
    <a href="{% acc_url 'member_create' %}">Add A New Board Member <i class="fa fa-arrow-right"></i></a>
  </div>
  <div class="steps text-center {% if has_meetings %}finished{% endif %}">
    <h3>Step 2: Add First Board Meeting.</h3>
    <p>Create your first Board Meeting and upload your first agenda, minutes and reports. Once<br/>you've created your first meeting, you'll need to invite them.</p>
    <a href="{% acc_url 'meetings:create' %}">Create Your First Meeting <i class="fa fa-arrow-right"></i></a>
  </div>
  <div class="steps text-center {% if has_documents %}finished{% endif %}">
    <h3>Step 3: Upload Your First Documents.</h3>
    <p>Create folders, subfolders and upload your first documents. By default, we've added some<br/>basic folders an organization may need. Feel free to add new, rename, or delete folders.</p>
    <a href="{% acc_url 'folders:rootfolder_detail'  %}">Upload Your First Documents <i class="fa fa-arrow-right"></i></a>
  </div>
  <div class="steps text-center {% if has_committees %}finished{% endif %}">
    <h3>Step 4: Create Your First Committee.</h3>
    <p>Create your first committee, add a chairperson, and invite board members. By default, we've added<br/>some committees an organization may need. Feel free to add new, rename, or delete committees.</p>
    <a href="{% acc_url 'committees:create' %}">Create Your First Committee <i class="fa fa-arrow-right"></i></a>
  </div>
  <div class="help-div">
    <div>
      <h4>Need Help?</h4>
      <p>If you have any questions, feel free to email us <a href="mailto:support@boarddirector.co">support@boarddirector.co</a></p>
    </div>
  </div>
  <div class="text-center">
    <a href="{% acc_url 'dashboard:getting_started' %}?show_guide=false" class="close-guide">CLOSE GUIDE <i class="fa fa-close"></i></a>
  </div>
</div>

<script id="close-guide-confirmation" type="text/x-kendo-template">
  <p class="delete-message">{% trans 'Are you sure you want to close the Getting Started Guide' %}?</p>
  <div class="confirmation-buttons">
    <button class="delete-confirm k-button">{% trans 'Yes' %}</button>
    <button class="delete-cancel k-button">{% trans 'No' %}</button>
  </div>
</script>
{% endblock workspace %}