apps/common/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django.views.generic import TemplateView

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.views.i18n import javascript_catalog

from .views import ContactView, PricingView, DomainView
from accounts.views import (AccountSettingsView, MembersView, GuestsView, MemberCreateView, GuestCreateView,
                            ExportMembersPdfView, ExportMembersXlsView, AssistantCreateView)
from documents.views import RootFolderRedirectView

admin.autodiscover()
dajaxice_autodiscover()


js_info_dict = {'packages': ('common',)}

urlpatterns = patterns(
    '',
    url(r'^privacy/$', flatpage, {'url': '/privacy/'}, name='privacy'),
    url(r'^terms/$', flatpage, {'url': '/terms/'}, name='terms'),
)

urlpatterns += patterns(
    'common.views',
    url(r'^', include('registration.backends.default.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    url(r'^mEOu0wA.html$', DomainView.as_view()),

    url(r'^$', 'main', name='main'),
    url(r'^app-admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', 'accounts')),
    url(r'^accounts/email/', include('change_email.urls')),
    url(r'^billing/', include('billing.urls', 'billing')),
    url(r'^profile/', include('profiles.urls', 'profiles')),
    url(r'^contact/thankyou/', TemplateView.as_view(template_name='thankyou.html'), name='thankyou'),
    url(r'^contact/', ContactView.as_view(), name='contactus'),
    url(r'^documents/', include('documents.urls.document', 'documents')),
    url(r'^pricing/', PricingView.as_view(), name='pricing'),
    url(r'^pricing-frame/', PricingView.as_view(template_name="pricing_frame.html"), name='pricing-frame'),

    url(r'^(?P<url>[^/]+)/$', AccountSettingsView.as_view(), name='board_detail'),
    url(r'^(?P<url>[^/]+)/archives/', RootFolderRedirectView.as_view()),
    url(r'^(?P<url>[^/]+)/folders/', include('documents.urls.folder', 'folders')),
    url(r'^(?P<url>[^/]+)/committees/', include('committees.urls', 'committees')),
    url(r'^(?P<url>[^/]+)/news/', include('news.urls', 'news')),
    url(r'^(?P<url>[^/]+)/calendar/', include('boardcalendar.urls', 'calendar')),
    url(r'^(?P<url>[^/]+)/dashboard/', include('dashboard.urls', 'dashboard')),
    url(r'^(?P<url>[^/]+)/rsvp/', include('rsvp.urls', 'rsvp')),
    url(r'^(?P<url>[^/]+)/meetings/', include('meetings.urls', 'meetings')),
    url(r'^(?P<url>[^/]+)/events/', include('meetings.events_urls', 'events')),
    url(r'^(?P<url>[^/]+)/members/$', MembersView.as_view(), name='board_members'),
    url(r'^(?P<url>[^/]+)/guests/$', GuestsView.as_view(), name='board_guests'),
    url(r'^(?P<url>[^/]+)/members/create/$', MemberCreateView.as_view(), name='member_create'),
    url(r'^(?P<url>[^/]+)/guests/create/$', GuestCreateView.as_view(), name='guest_create'),
    url(r'^(?P<url>[^/]+)/assistant/(?P<pk>\d+)/create/$', AssistantCreateView.as_view(), name='assistant_create'),
    url(r'^(?P<url>[^/]+)/export/pdf/$', ExportMembersPdfView.as_view(), name='export-pdf'),
    url(r'^(?P<url>[^/]+)/export/xls/$', ExportMembersXlsView.as_view(), name='export-xls'),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from .views import NewsListView, NewsDetailView, NewsCreateView, NewsUpdateView, NewsDeleteView


urlpatterns = patterns(
    'news.views',
    url(r'^create/$', NewsCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', NewsUpdateView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)/$', NewsDeleteView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/$', NewsDetailView.as_view(), name='detail'),
    url(r'^$', NewsListView.as_view(), name='list')
)

apps/profiles/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from .views import EditProfileView, MemberView, MembershipDeleteView, InviteMemberView, AssistantView, EditAssistantView, \
    AssistantDeleteView


urlpatterns = patterns(
    'profiles.views',
    url(r'^edit/(?P<pk>\d+)/$', EditProfileView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)/$', MembershipDeleteView.as_view(), name='delete'),
    url(r'^edit/(?P<member_pk>\d+)/(?P<pk>\d+)/$', EditAssistantView.as_view(), name='assistant_edit'),
    url(r'^delete/(?P<member_pk>\d+)/(?P<pk>\d+)/$', AssistantDeleteView.as_view(), name='assistant_delete'),
    url(r'^(?P<pk>\d+)/$', MemberView.as_view(), name='detail'),
    url(r'^(?P<member_pk>\d+)/(?P<pk>\d+)/assistant/$', AssistantView.as_view(), name='assistant_detail'),
    url(r'^invite/(?P<user_pk>\d+)/$', InviteMemberView.as_view(), name='invite'),
    url(r'^$', MemberView.as_view(), name='detail'),
)

apps/profiles/models.py
# -*- coding: utf-8 -*-
import urlparse

from django.conf import settings
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.contrib.auth.signals import user_logged_in
from django.contrib.sites.models import Site
from django.core.files.storage import FileSystemStorage
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.db import models
from django.dispatch import receiver
from django.shortcuts import get_object_or_404
from django.template import Context
from django.template.loader import get_template_from_string
from django.utils import timezone
from django.utils.translation import ugettext as _

from croppy.fields import CropField
from sorl.thumbnail import get_thumbnail
from timezone_field.fields import TimeZoneField

from accounts.models import Account
from committees.models import Committee
from common.choices import Choices
from common.models import TemplateModel
from common.storage_backends import StableS3BotoStorage
from common.utils import avatar_upload_to, crops_upload_to


if settings.USE_S3:
    avatar_storage = StableS3BotoStorage(file_overwrite=False)
else:
    avatar_storage = FileSystemStorage(location=settings.AVATAR_ROOT, base_url=settings.AVATAR_URL)


class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = UserManager.normalize_email(email)
        user = self.model(email=email, is_staff=False, is_active=True, is_superuser=False, **extra_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        u = self.create_user(email, password, **extra_fields)
        u.is_staff = True
        u.is_active = True
        u.is_superuser = True
        u.save(using=self._db)
        return u

    def get_by_natural_key(self, username):
        return self.get(**{self.model.USERNAME_FIELD + '__iexact': username})


class User(AbstractBaseUser):
    email = models.EmailField(_('email address'), unique=True)

    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text=_('Designates whether the user can log into this admin site.'))
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this user should be treated as '
                                    'active. Unselect this instead of deleting accounts.'))
    is_superuser = models.BooleanField(_('superuser status'), default=False,
                                       help_text=_('Designates that this user has all permissions without '
                                       'explicitly assigning them.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    accounts = models.ManyToManyField(Account, through='Membership', verbose_name=_('accounts'),
                                      related_name='users', null=True)

    USERNAME_FIELD = 'email'
    objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def _get_name(self):
        memberships = self.membership_set.all()
        if memberships:
            return {"first": memberships[0].first_name,
                    "last": memberships[0].last_name}
        else:
            return None

    def get_full_name(self):
        n = self._get_name()
        if n:
            full_name = u"{0} {1}".format(n.get("first"), n.get("last")).strip()
        else:
            full_name = None
        return full_name or self.email

    def get_short_name(self):
        n = self._get_name()
        if n:
            first_name = n.get("first", "").strip()
        else:
            first_name = None
        return first_name or self.email.split('@')[0]

    def get_membership(self, account):
        membership_name = '_membership_{}'.format(account.id)
        if not hasattr(self, membership_name):
            membership = get_object_or_404(Membership, user=self, account=account)
            setattr(self, membership_name, membership)
        return getattr(self, membership_name)

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def get_absolute_url(self):
        return reverse('profiles:detail', kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.email

    def send_invitation_email(self, account, password=None, message=None, from_member=None):
        site = Site.objects.get_current()
        ctx_dict = {'account': account, 'user': self}
        ctx_dict['inviter'] = str(from_member or 'Someone')
        protocol = settings.SSL_ON and 'https' or 'http'
        ctx_dict['protocol'] = protocol
        if password:
            ctx_dict['password'] = password
            ctx_dict['profile_detail_url'] = \
                urlparse.urljoin('{}://{}'.format(protocol, site),
                                 reverse('profiles:detail',
                                 kwargs={'pk': self.get_membership(account).pk}))
        ctx_dict['board_detail_url'] = urlparse.urljoin('{}://{}'.format(protocol, site),
                                                        reverse('board_detail', kwargs={'url': account.url}))
        ctx_dict['login_link'] = urlparse.urljoin('{}://{}'.format(protocol, site), reverse('auth_login'))
        if message:
            # Fixme: should it be preprocessed?
            ctx_dict['message'] = message

        tmpl = TemplateModel.objects.get(name=TemplateModel.INVITE)
        subject = tmpl.title
        message = tmpl.generate(ctx_dict)
        self.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)

    def admin_notification(self, account, msg_type='cancel_account'):
        site = Site.objects.get_current()
        ctx_dict = {'account': account, 'site': site, 'user': self, 'protocol': settings.SSL_ON and 'https' or 'http'}
        tmpl, message = '', ''
        if msg_type == 'cancel_account':
            ctx_dict['url'] = reverse('accounts:boards')
            tmpl = TemplateModel.objects.get(name=TemplateModel.CANCEL)
            message = tmpl.generate(ctx_dict)
        elif msg_type == 'trial_is_over':
            ctx_dict['url'] = reverse('billing:update_settings')
            if account.stripe_customer_id:
                tmpl = TemplateModel.objects.get(name=TemplateModel.TRIAL)
            else:
                tmpl = TemplateModel.objects.get(name=TemplateModel.TRIAL_IS_OVER_CANCEL)
            message = tmpl.generate(ctx_dict)
        elif msg_type == 'paid_is_over':
            tmpl = TemplateModel.objects.get(name=TemplateModel.PAID)
            message = tmpl.generate(ctx_dict)
        elif msg_type == 'trial_reminder':
            ctx_dict['date_cancel'] = (account.date_created +
                                       timezone.timedelta(days=settings.TRIAL_PERIOD)).strftime('%b %d, %Y')
            tmpl = TemplateModel.objects.get(name=TemplateModel.TRIAL_REMINDER)
            message = tmpl.generate(ctx_dict)

        subject = get_template_from_string(tmpl.title)
        subject = subject.render(Context(ctx_dict))
        self.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)

    def email_user(self, subject, message, from_email=None, attachments=()):
        """
        Sends an email to this User.
        """
        msg = EmailMessage(subject, message, from_email, [self.email])
        for name, attach, content_type in attachments:
            msg.attach(name, attach, content_type)
        msg.content_subtype = 'html'
        msg.send()


class Membership(models.Model):
    ROLES = Choices(
        (0, 'admin', _('Administrator')),
        (1, 'chair', _('Board Chair')),
        (2, 'member', _('Board Member')),
        (3, 'assistant', _('Executive Assistant')),
        (4, 'guest', _('Guest')),
        (5, 'vendor', _('Vendor')),
        (6, 'staff', _('Staff')),
        (7, 'consultant', _('Consultant'))
    )
    STATUS = Choices(
        (True, 'active', _('Active')),
        (False, 'inactive', _('Inactive')),
    )
    INV_NOT_SENT, INV_SENT, INV_INVITED = range(3)
    INV_CHOICES = (
        (INV_NOT_SENT, 'NOT_SENT'),
        (INV_SENT, 'SENT'),
        (INV_INVITED, 'INVITED'))
    user = models.ForeignKey(User)
    assistant = models.ForeignKey('self', related_name='bosses', blank=True, null=True)
    account = models.ForeignKey(Account, related_name='memberships')
    committees = models.ManyToManyField(Committee, verbose_name=_('committees'),
                                        related_name='memberships', blank=True, null=True)
    date_joined_board = models.DateField(_('date joined board'), default=timezone.now)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    phone_number = models.CharField(_('phone number'), max_length=255, blank=True)
    role = models.PositiveSmallIntegerField(_('role'), choices=ROLES, default=ROLES.admin)
    is_active = models.BooleanField(_('active'), choices=STATUS, default=True)
    term_start = models.DateField(_('starts'), blank=True, null=True)
    term_expires = models.DateField(_('expires'), blank=True, null=True)
    timezone = TimeZoneField(default=settings.TIME_ZONE)
    employer = models.CharField(_('employer'), max_length=255, blank=True)
    job_title = models.CharField(_('job title'), max_length=255, blank=True)
    work_email = models.CharField(_('work email'), max_length=255, blank=True)
    work_number = models.CharField(_('work number'), max_length=255, blank=True)
    intro = models.CharField(_('intro'), max_length=250, blank=True)
    bio = models.TextField(_('bio'), blank=True)

apps/common/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.safestring import mark_safe
from .models import Feedback, TemplateModel


class ContactForm(forms.ModelForm):
    class Meta:
        model = Feedback


class RichTextWidget(forms.Textarea):
    class Media:
        css = {
            'all': ('css/kendo.common.min.css', 'css/kendo.default.min.css')
        }
        js = ('js/jquery-1.8.3.min.js', 'js/kendo.web.min.js', 'js/preview.js')

    def render(self, name, value, attrs=None):
        return mark_safe(super(RichTextWidget, self).render(name, value, attrs))


class TemplateForm(forms.ModelForm):
    class Meta:
        model = TemplateModel
        widgets = {
            'html': RichTextWidget(attrs={'class': 'kendo_editor', 'style': 'height: 500px;'})
        }

apps/common/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.views.generic import TemplateView, CreateView, View
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect

from .forms import ContactForm
from .models import Feedback
from billing.models import Plan


class MainView(TemplateView):
    template_name = 'index.html'


class ContactView(CreateView):
    model = Feedback
    template_name = 'contactus.html'
    form_class = ContactForm
    success_url = reverse_lazy('thankyou')

    def form_valid(self, form):
        form.save()
        return redirect(self.success_url)


class PricingView(TemplateView):
    template_name = 'pricing.html'

    def get_context_data(self, **kwargs):
        ctx = super(PricingView, self).get_context_data(**kwargs)
        ctx['plans'] = Plan.list_available_plans()
        ctx['show_trial_button'] = True
        return ctx


class DomainView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse('mEOu0wA')

main = MainView.as_view()

apps/common/templates/profiles/includes/members_detail.html
{% load i18n user_tags permissions_tags %}
  <div class="bio-holder">
    {% if membership_object %}
      <h2>{{ membership_object.get_full_name }}</h2>
      <h3><span>{{ membership_object.get_role_display }}</span></h3>
      <div class="photo">
        <img src="{{ membership_object|avatar:'360x270' }}" height="270" alt="image description">
      </div>
      <h4>{{ membership_object.intro }}</h4>
      <div class="member-bio">{{ membership_object.bio|safe }}</div>
      <dl>
        <dt>{% trans 'Joined Board' %}:</dt>
        <dd>{{ membership_object.date_joined_board|date:"N j, Y" }}</dd>
        {% if membership_object.role < 4 %}
        <dd class="divider">|</dd>
        <dt>{% trans 'Term Expires' %}:</dt>
        <dd>{{ membership_object.term_expires|date:"N j, Y"|default:'-' }}</dd>
        {% endif %}
      </dl>
      {% if membership_object.role != request.user.ASSISTANT %}
        <dl>
          <dt>{% trans "Committes" %}:</dt>
          <dd>{% for commi in membership_object.committees.all %}
            <a href="{{ commi.get_absolute_url }}">{{ commi.name }}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}</dd>
        </dl>
      {% endif %}
      <dl>
        <dt>{% trans 'Profile Last Changed on' %}:</dt>
        <dd>{{ membership_object.last_modified|date:"N j, Y"|default:'-' }}</dd>
      </dl>
      {% if membership_object.position %}
        <dl>
          <dt>{% trans 'Profile Position' %}:</dt>
          <dd>{{ membership_object.position }}</dd>
        </dl>
      {% endif %}
      {% if membership_object.employer %}
        <dl>
          <dt>{% trans 'Employer' %}:</dt>
          <dd>{{ membership_object.employer }}</dd>
        </dl>
      {% endif %}
      {% if membership_object.job_title %}
        <dl>
          <dt>{% trans 'Job Title' %}:</dt>
          <dd>{{ membership_object.job_title }}</dd>
        </dl>
      {% endif %}
      {% if membership_object.get_affiliation %}
        <dl>
          <dt>{% trans 'Affiliation' %}:</dt>
          <dd>{{ membership_object.get_affiliation }}</dd>
        </dl>
      {% endif %}
      {% if membership_object.get_phone %}
        <dl>
          <dt>{% trans 'Phone Numbers' %}:</dt>
          <dd>{{ membership_object.get_phone }}</dd>
        </dl>
      {% endif %}
      {% if membership_object.assistant %}
        <dl>
          <dt>{% trans 'Assistant' %}:</dt>
          <dd>
            <a href="{% url 'profiles:assistant_detail' member_pk=membership_object.pk pk=membership_object.assistant.pk %}">
              {{ membership_object.assistant.get_full_name }}
            </a>
          </dd>
        </dl>
      {% endif %}
      <ul class="contacts">
        {% if membership_object.account.view_email or current_membership|has_role_permission:'profiles.membership:add' %}
          <li><a class="email" href="mailto:{{ membership_object.user.email }}">{{ membership_object.user.email }}</a></li>
        {% endif %}
        {% if membership_object.social_media_link %}
          <li>
            <a id="id_social_media_link" href="{{ membership_object.social_media_link }}" target="_blank"></a>
          </li>
        {% endif %}
      </ul>
    {% endif %}
  </div>

  <script id="delete-confirmation" type="text/x-kendo-template">
    <p class="delete-message">{% trans 'Are you sure you want to deactivate this profile' %}?</p>
    <div class="confirmation-buttons">
      <button class="delete-confirm k-button">{% trans 'Yes' %}</button>
      <button class="delete-cancel k-button">{% trans 'No' %}</button>
    </div>
  </script>

apps/common/templates/profiles/includes/profiles_form.html
<ul class="fields-list">
  {% for field in form.visible_fields %}
    {% if field.name != 'avatar' %}
      {% if field.name == 'first_name' %}
        {% if form.instance.role < 4 %}<h2>Member Details</h2>{% else %}<h2>Guest Details</h2>{% endif %}
      {% elif field.name == 'employer' %}
        <hr>
        <h2>Work Details</h2>
      {% elif field.name == 'intro' %}
        <hr>
        <h2>Biography</h2>
      {% elif field.name == 'address' %}
        <hr>
        <h2>Personal Details(Private)</h2>
      {% elif field.name == 'affiliation' %}
        <hr>
        <h2>Social Details</h2>
      {% endif %}
      <li
        {% if field.name == 'term_start' %}
          class="start-date"
        {% elif field.name == 'term_expires' %}
          class="end-date"
        {% elif field.name == 'intro' or field.name == 'bio' or field.name == 'address' or field.name == 'secondary_address' %}
          class="two-columns"
        {% elif field.name == 'affiliation' or field.name == 'social_media_link' %}
          class="social-details"
        {% endif %}
      >
      <label for="{{ field.name }}" {% if field.field.required %} class="special_class" {% endif %}>
        {{ field.label }}
      </label>
      {% if field.name == 'affiliation' or field.name == 'social_media_link' %}
        <div class="list-value-field">
          {{ field }}
          <div class="remove" hidden></div>
        </div>
      {% else %}
        {{ field }}
      {% endif %}
        {% if field.errors %}
        <span class="k-widget k-tooltip k-tooltip-validation k-invalid-msg" data-for="{{ field.auto_id }}" role="alert">
          <span class="k-icon k-warning"></span>
          {{ field.errors.0 }}
        </span>
        {% endif %}
      </li>
      {% if field.name == 'social_media_link' %}
        <hr>
      {% endif %}
    {% endif %}
  {% endfor %}
</ul>