apps/common/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django.views.generic import TemplateView

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.views.i18n import javascript_catalog

from .views import ContactView, PricingView, DomainView
from accounts.views import (AccountSettingsView, MembersView, GuestsView, MemberCreateView, GuestCreateView,
                            ExportMembersPdfView, ExportMembersXlsView, AssistantCreateView)
from documents.views import RootFolderRedirectView

admin.autodiscover()
dajaxice_autodiscover()


js_info_dict = {'packages': ('common',)}

urlpatterns = patterns(
    '',
    url(r'^privacy/$', flatpage, {'url': '/privacy/'}, name='privacy'),
    url(r'^terms/$', flatpage, {'url': '/terms/'}, name='terms'),
)

urlpatterns += patterns(
    'common.views',
    url(r'^', include('registration.backends.default.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    url(r'^mEOu0wA.html$', DomainView.as_view()),

    url(r'^$', 'main', name='main'),
    url(r'^app-admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', 'accounts')),
    url(r'^accounts/email/', include('change_email.urls')),
    url(r'^billing/', include('billing.urls', 'billing')),
    url(r'^profile/', include('profiles.urls', 'profiles')),
    url(r'^contact/thankyou/', TemplateView.as_view(template_name='thankyou.html'), name='thankyou'),
    url(r'^contact/', ContactView.as_view(), name='contactus'),
    url(r'^documents/', include('documents.urls.document', 'documents')),
    url(r'^pricing/', PricingView.as_view(), name='pricing'),
    url(r'^pricing-frame/', PricingView.as_view(template_name="pricing_frame.html"), name='pricing-frame'),

    url(r'^(?P<url>[^/]+)/$', AccountSettingsView.as_view(), name='board_detail'),
    url(r'^(?P<url>[^/]+)/archives/', RootFolderRedirectView.as_view()),
    url(r'^(?P<url>[^/]+)/folders/', include('documents.urls.folder', 'folders')),
    url(r'^(?P<url>[^/]+)/committees/', include('committees.urls', 'committees')),
    url(r'^(?P<url>[^/]+)/news/', include('news.urls', 'news')),
    url(r'^(?P<url>[^/]+)/calendar/', include('boardcalendar.urls', 'calendar')),
    url(r'^(?P<url>[^/]+)/dashboard/', include('dashboard.urls', 'dashboard')),
    url(r'^(?P<url>[^/]+)/rsvp/', include('rsvp.urls', 'rsvp')),
    url(r'^(?P<url>[^/]+)/meetings/', include('meetings.urls', 'meetings')),
    url(r'^(?P<url>[^/]+)/events/', include('meetings.events_urls', 'events')),
    url(r'^(?P<url>[^/]+)/members/$', MembersView.as_view(), name='board_members'),
    url(r'^(?P<url>[^/]+)/guests/$', GuestsView.as_view(), name='board_guests'),
    url(r'^(?P<url>[^/]+)/members/create/$', MemberCreateView.as_view(), name='member_create'),
    url(r'^(?P<url>[^/]+)/guests/create/$', GuestCreateView.as_view(), name='guest_create'),
    url(r'^(?P<url>[^/]+)/assistant/(?P<pk>\d+)/create/$', AssistantCreateView.as_view(), name='assistant_create'),
    url(r'^(?P<url>[^/]+)/export/pdf/$', ExportMembersPdfView.as_view(), name='export-pdf'),
    url(r'^(?P<url>[^/]+)/export/xls/$', ExportMembersXlsView.as_view(), name='export-xls'),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from .views import NewsListView, NewsDetailView, NewsCreateView, NewsUpdateView, NewsDeleteView


urlpatterns = patterns(
    'news.views',
    url(r'^create/$', NewsCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', NewsUpdateView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)/$', NewsDeleteView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/$', NewsDetailView.as_view(), name='detail'),
    url(r'^$', NewsListView.as_view(), name='list')
)

apps/common/models.py
# -*- coding: utf-8 -*-
from django.contrib.sites.models import Site
from django.db import models
from django.template import Context
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
from django.dispatch import receiver
from django.template.loader import render_to_string, get_template_from_string
from django.conf import settings


class Feedback(models.Model):
    email = models.EmailField(_('email address'))
    message = models.TextField(_('message'))
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Feedback')
        verbose_name_plural = _('Feedbacks')

    def send_feedback(self):
        ctx_dict = {'email': self.email}
        subject = render_to_string('registration/feedback_email_subject.txt',
                                   ctx_dict)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        self.message = self.message + '\n' + Site.objects.get_current().domain
        send_mail(subject, self.message, self.email, [i[1] for i in settings.ADMINS])

    def __unicode__(self):
        return 'Feedback from {}'.format(self.email)


@receiver(models.signals.post_save, sender=Feedback)
def send_feedback_via_email(sender, created, instance, **kwargs):
    if created:
        instance.send_feedback()


class TemplateModel(models.Model):
    (ACTIVATE, RESET, MEETING, INVITE, CANCEL, TRIAL, TRIAL_IS_OVER_CANCEL,
     PAID, TRIAL_REMINDER, DOC, DOCUMENT_UPDATED, MEETING_REMINDER) = range(1, 13)

    CHOICES = (
        (ACTIVATE, _('account activation template')),
        (RESET, _('password reset template')),
        (MEETING, _('meeting invitation template')),
        (INVITE, _('member invitation template')),
        (CANCEL, _('account canceled template')),
        (TRIAL, _('trial is over template')),
        (TRIAL_IS_OVER_CANCEL, _('trial is over and account cancel template')),
        (PAID, _('paid is over template')),
        (TRIAL_REMINDER, _('trial reminder template')),
        (DOC, _('add document template')),
        (DOCUMENT_UPDATED, _('document updated template')),
        (MEETING_REMINDER, _('meeting reminder updated template'))
    )

    name = models.IntegerField(_('name'), max_length=100, choices=CHOICES, unique=True, editable=False)
    title = models.CharField(_('subject'), max_length=100)
    html = models.TextField(_('content'), help_text=_('Do not change text in braces'))

    def __unicode__(self):
        return self.get_name_display().title()

    def generate(self, content):
        content['title'] = self.title
        t = get_template_from_string(self.html)
        return t.render(Context(content))

    class Meta:
        verbose_name = _('Template editor')
        verbose_name_plural = _('Template editors')

apps/customer_io/models.py
# -*- coding: utf-8 -*-
from . import signals  # noqa

apps/news/models.py
# -*- coding: utf-8 -*-
import urlparse
from django.conf import settings
from django.core.urlresolvers import reverse

from django.db import models
from django.utils.translation import ugettext as _
from sorl.thumbnail import get_thumbnail
from accounts.models import Account
from documents.models import file_storage

from profiles.models import Membership


class News(models.Model):
    title = models.CharField(_('title'), max_length=255, unique=True)
    text = models.TextField(_('text'))
    created_at = models.DateTimeField(_('date created'), auto_now=True)
    file = models.ImageField(_('image'), upload_to='uploads/news/%Y%m%d', storage=file_storage, null=True, blank=True)
    created_member = models.ForeignKey(Membership, verbose_name=_('member'))
    account = models.ForeignKey(Account, verbose_name=_('account'))
    is_publish = models.BooleanField(_('published'), default=True)

    class Meta:
        ordering = ('-created_at',)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('news:detail', kwargs={'pk': self.pk, 'url': self.account.url})

    def list_photo_url(self, geometry='180x120'):
        if self.file:
            return get_thumbnail(self.file, geometry, crop='center', quality=100).url
        return urlparse.urljoin(settings.STATIC_URL, 'images/news.png')

apps/common/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.safestring import mark_safe
from .models import Feedback, TemplateModel


class ContactForm(forms.ModelForm):
    class Meta:
        model = Feedback


class RichTextWidget(forms.Textarea):
    class Media:
        css = {
            'all': ('css/kendo.common.min.css', 'css/kendo.default.min.css')
        }
        js = ('js/jquery-1.8.3.min.js', 'js/kendo.web.min.js', 'js/preview.js')

    def render(self, name, value, attrs=None):
        return mark_safe(super(RichTextWidget, self).render(name, value, attrs))


class TemplateForm(forms.ModelForm):
    class Meta:
        model = TemplateModel
        widgets = {
            'html': RichTextWidget(attrs={'class': 'kendo_editor', 'style': 'height: 500px;'})
        }

apps/common/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.views.generic import TemplateView, CreateView, View
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect

from .forms import ContactForm
from .models import Feedback
from billing.models import Plan


class MainView(TemplateView):
    template_name = 'index.html'


class ContactView(CreateView):
    model = Feedback
    template_name = 'contactus.html'
    form_class = ContactForm
    success_url = reverse_lazy('thankyou')

    def form_valid(self, form):
        form.save()
        return redirect(self.success_url)


class PricingView(TemplateView):
    template_name = 'pricing.html'

    def get_context_data(self, **kwargs):
        ctx = super(PricingView, self).get_context_data(**kwargs)
        ctx['plans'] = Plan.list_available_plans()
        ctx['show_trial_button'] = True
        return ctx


class DomainView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse('mEOu0wA')

main = MainView.as_view()

apps/common/templates/base.html
{% load i18n static compress %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>{% block title %}Board of Directors Cloud Management Software{% endblock title %}</title>
  <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <link href="{% static 'css/chosen.min.css' %}" rel="stylesheet"/>
  <link href="{% static 'css/kendo.common.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/kendo.default.min.css' %}" rel="stylesheet" />
  {% compress css %}
    <link media="all" rel="stylesheet" href="{% static 'css/all.css' %}">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
  {% endcompress %}
  {% block extra_css %}{% endblock extra_css %}
  <script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
  <script src="{% static 'js/jquery.cookie-1.4.1.min.js' %}"></script>
  <script src="{% static 'js/chosen.jquery.min.js' %}"></script>
  {% compress js %}
    <script src="{% static 'js/main.js' %}"></script>
  {% endcompress %}
  <script>(function(doc){var viewport = document.getElementById('viewport');if (navigator.userAgent.match(/iPad/i)){doc.getElementById("viewport").setAttribute("content", "initial-scale=1.0");}}(document));</script>
  <!--[if lt IE 9]>
  <script type="text/javascript" src="{% static 'js/modernizr.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/css3-mediaqueries.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/PIE.js' %}"></script>
  <![endif]-->
  <script type="text/javascript" src="/jsi18n/"></script>
  <script>
    var USER_EMAIL = '{{ request.user.email }}';
    var USER_NAME = '{{ current_membership.get_full_name }}';
  </script>
  <script src="{% static 'js/uservoice.js' %}"></script>
  {# <script src="{% static 'js/hotjar.js' %}"></script> #}
  <script src="{% static 'js/scripts.js' %}"></script>
  {% block extra_js %}{% endblock extra_js %}
</head>
<body>
  <div class="ls-wrapper">
    {% block content %}
    {% endblock content %}
    <div class="substrate-footer"></div>
  </div>
  <footer id="footer">
    <div class="wrapper">
      {% block footer %}{% endblock %}
      {% include "footer.html" %}
    </div>
  </footer>
  <div id="pdf-wrapper">
    <iframe id="pdf-viewer"></iframe>
  </div>
  {% include "customer_io.html" %}
  {% include "chameleon.html" %}
</body>
</html>

apps/common/templates/blank_form.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>Board of Directors Cloud Management Software</title>
  <link media="all" rel="stylesheet" href="{% static 'css/styles-external.css' %}">
  <link media="all" rel="stylesheet" href="{% static 'css/passwordstrenght.css' %}">
  <link href="{% static 'css/kendo.common.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/kendo.default.min.css' %}" rel="stylesheet" />
  {% block extra_css %}{% endblock extra_css %}

  <script type="text/javascript" src="{% static 'js/password.js' %}"></script>
  <script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
  <!--[if lt IE 9]>
    <script type="text/javascript" src="{% static 'js/modernizr.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/PIE.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/css3-mediaqueries.js' %}"></script>
  <![endif]-->
  <script>
    var USER_EMAIL = '{{ request.user.email }}';
    var USER_NAME = '{{ current_membership.get_full_name }}';
  </script>
  {% block extra_js %}{% endblock extra_js %}
</head>
<body class="frame">
  <div id="page_wrapper">
    {% block content %}
    {% endblock content %}
  </div>
</body>
</html>

apps/common/templates/chameleon.html
{% if chameleon_enabled and current_membership != None %}
  <script>
    !function(t,n,o){var a="chmln",c="setup identify alias track set show on off custom help _data".split(" ");n[a]||(n[a]={}),n[a].accountToken=o,n[a].location=n.location.href.toString();for(var e=0;e<c.length;e++)!function(){var t=n[a][c[e]+"_a"]=[];n[a][c[e]]=function(){t.push(arguments)}}();var s=t.createElement("script");s.src="https://fast.trychameleon.com/messo/"+o+"/messo.min.js",s.async=!0,t.head.appendChild(s)}(document,window,"SAtlPjYMWGA1jiV7AYF1D38gSa7SE9xEoRdJwPkr58eIyh-1C3H6Z-ztbpXMzr0tGiPmve");
    chmln.identify({
      uid: '{{ current_membership.id }}',
      email: '{{ current_membership.user.email }}',
      created: '{{ current_membership.user.date_joined|date:"U" }}',
      user_role: '{{ current_membership.get_role_display }}'
    });
  </script>
{% endif %}

apps/common/templates/customer_io.html
{% if customerio_enabled and current_membership != None %}
  <script type="text/javascript">
    var _cio = _cio || [];
    (function() {
      var a,b,c;a=function(f){return function(){_cio.push([f].
      concat(Array.prototype.slice.call(arguments,0)))}};b=["identify",
      "track"];for(c=0;c<b.length;c++){_cio[b[c]]=a(b[c])};
      var t = document.createElement('script'),
          s = document.getElementsByTagName('script')[0];
      t.async = true;
      t.id    = 'cio-tracker';
      t.setAttribute('data-site-id', '{{ customerio_site_id }}');
      t.src = '//assets.customer.io/assets/track.js';
      s.parentNode.insertBefore(t, s);
    })();
  </script>
  <script type="text/javascript">
    _cio.identify({
      id: '{{ current_membership.id }}',
      email: '{{ current_membership.user.email }}',
      last_login: '{{ current_membership.last_login|date:"U" }}'
    });
  </script>
{% endif %}

apps/common/templates/doc_upd_popup.html
{% load i18n static %}
{% load dajaxice_templatetags common_tags %}

<form action="#">
  <div class="update-archive-popup">
    <div data-url=""
       id="update-archive-dialog"
       title="{% trans "Upload new version" %}"
       data-cancel-button-text="{% trans 'or Cancel' %}"
       data-send-button-text="{% trans 'Upload new version' %}"
    >
      <div class="update-archive-form">
        <p class="replace-file-wrapper">
          <span class="replace-file-label">{% trans "File to replace:" %}</span>
          <span id="doc-filename"></span>
        </p>
        <div id="update-archive-file-wrapper"></div>
        <div id="update-archive-email-wrapper">
          <p>
            <span id="email-recipient"></span> {% trans "will be notified of this change" %}
          </p>
          <div>
            <label class="notify-label" for="browse-by">{% trans 'Notify by email' %}:</label>
            <select id="browse-by" name="show">
              <option value="" selected>{% trans 'Nobody' %}</option>
              {% if committees|length == 1 %}
                {% for committee in committees %}
                  <option value="{{ committee.pk }}">{{ committee.name }}</option>
                {% endfor %}
              {% elif committees|length > 1 %}
                <option value="-1">{% trans 'All Committees' %}</option>
                {% for committee in committees %}
                  <option value="{{ committee.pk }}">{{ committee.name }}</option>
                {% endfor %}
              {% endif %}
            </select>
          </div>
        </div>
        <div class="notify-me-wrapper">
          <input class="notify-me-checkbox" type="checkbox" name="notify_me" id="notify_me"><label for="notify_me">{% trans 'Send me a copy' %}</label>
        </div>
      </div>
    </div>
  </div>
</form>
{% if folder %}
  <form method="post" enctype="multipart/form-data" class="create-document-form" action="{% acc_url 'folders:document_add' slug=folder.slug %}" hidden>
    {% csrf_token %}
    <input id="id_file" name="file" type="file" data-role="upload" autocomplete="off">
    <input id="id_uploaded_file" name="uploaded_file" type="hidden">
    <input id="id_notify_group" name="notify_group" type="hidden">
    <input id="id_notify_me" name="notify_me" type="hidden">
  </form>
{% endif %}

apps/common/templates/footer.html
{% load i18n %}

<div class="footer-bar">
  Copyright, &copy; 2014 BOARD DIRECTOR, LLC. , All Right Reserved. /
  <a href="https://twitter.com/boarddirectorco">Twitter</a>
  / <a href="{% url 'privacy' %}">{% trans "PRIVACY POLICY" %}</a>*
</div>

apps/common/templates/form.html
{% load i18n %}
{% for hidden in form.hidden_fields %}
  {{ hidden }}
{% endfor %}
  {% if form.non_field_errors %}
  <span class="k-widget k-tooltip k-tooltip-validation k-invalid-msg" role="alert">
    <span class="k-icon k-warning"></span>
    {{ form.non_field_errors.0 }}
  </span>
  {% endif %}
{% for field in form.visible_fields %}
  {% if field.name != 'time_end' %}
  <li>
  {% endif %}
  {% if field.name == 'name' %}
    {{ field }}
  {% elif field.field.type == 'file' %}
    <span class="label">{{ field.label }}</span>
    {{ field }}
  {% elif field.name == 'description' %}
    {{ field.label_tag }}
    <div class="textarea">
      {{ field }}
    </div>
  {% else %}
    {{ field.label_tag }}
    {{ field }}
  {% endif %}
  {% if field.errors %}
  <span class="k-widget k-tooltip k-tooltip-validation k-invalid-msg" data-for="{{ field.auto_id }}" role="alert">
    <span class="k-icon k-warning"></span>
    {{ field.errors.0 }}
  </span>
  {% endif %}

  {% if field.name != 'time_start' %}
  </li>
  {% endif %}
{% endfor %}

apps/common/templates/google_analytic.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53946639-1', 'auto');
  ga('send', 'pageview');
</script>

apps/common/templates/index.html
{% extends "registration/base.html" %}

{% block content %}
  <div class="visual">
    <div class="wrapper">
      <div class="text">
        <h2>Manage Your Board</h2>
        <h3>Your board of director essentials in one convenient and secure location</h3>
        <a class="btn" href="{% url 'registration_register' %}">TRY IT FOR FREE</a>
        <p class="note">No credit card required. Be up in minutes.</p>
      </div>
      <div class="ipad-holder">
        <img src="{{ STATIC_URL }}images-external/img2.jpg" width="342" height="250" alt="">
      </div>
    </div>
  </div>
  <div id="main">
    <article class="content">
      <section class="block">
        <hgroup>
          <h3>Board Management Made Simple</h3>
          <h4>A simple and elegant solution for board management delivered securely in the cloud.</h4>
        </hgroup>
        <div class="holder">
          <div class="img"><img src="{{ STATIC_URL }}images-external/img3.jpg" width="523" height="320" alt="image description"></div>
          <div class="text">
            <h4>No&#45;fuss management</h4>
            <ul class="list">
              <li>Compliance for secure storage of board documents</li>
              <li>Easy&#45;to&#45;locate records of meetings, minutes and reports</li>
              <li>No more wondering who has which documents</li>
              <li>Centralized calendaring for board directors</li>
            </ul>
            <a class="btn" href="{% url 'registration_register' %}">TRY IT FOR FREE</a>
            <p class="note">No credit card required. BE UP in minutes.</p>
          </div>
        </div>
      </section>
      <section class="boxes">
        <h3>Simple, Powerful and Secure Board Management</h3>
        <div class="holder">
          <div class="box">
            <h4>Manage Organization</h4>
            <p>Add and update information about your organization. No software to download, just log in and get organized. Your docs are accessible from anywhere.</p>
            <div class="img"><img src="{{ STATIC_URL }}images-external/ico1.png" width="64" height="64" alt=""></div>
            <span class="divider"></span>
          </div>
          <div class="box">
            <h4>Manage Directors</h4>
            <p>Add and update information about your Directors in the organization including Officers, Committees and service start and term end dates.</p>
            <div class="img"><img src="{{ STATIC_URL }}images-external/ico2.png" width="64" height="64" alt=""></div>
            <span class="divider"></span>
          </div>
          <div class="box">
            <h4>Manage Documents</h4>
            <p>Upload PDFs or Word Docs connected to board meeting dates, and securely store your documents in one location where everyone knows where to find them.</p>
            <div class="img"><img src="{{ STATIC_URL }}images-external/ico3.png" width="64" height="64" alt=""></div>
          </div>
        </div>
      </section>
      <section class="built-boards">
        <div class="img"><img src="{{ STATIC_URL }}images-external/img4.png" width="594" height="420" alt="image description"></div>
        <div class="text">
          <h3>Built for organizing boards</h3>
          <ul class="list">
            <li>Manage members and terms</li>
            <li>Organize and populate committees</li>
            <li>Schedule meetings</li>
            <li>Share agendas in advance</li>
            <li>Archive documents for audit purposes</li>
            <li>Retrieve all information easily and securely</li>
          </ul>
          <a class="btn" href="{% url 'registration_register' %}">Try for Free</a>
        </div>
      </section>
      <div class="trial-holder">
        <p><span>{{ trial_period }}-DAY free trial.</span>  Start managing your board in minutes.</p>
        <a class="btn" href="{% url 'registration_register' %}">Get Started</a>
      </div>
    </article>
  </div>
  {% include 'google_analytic.html' %}
{% endblock %}

apps/common/templates/inner.html
{% extends "base.html" %}
{% load common_tags static user_tags %}
{% load i18n %}
{% block extra_css %}

{% endblock extra_css %}
{% block title %}{{ block.super }}{% endblock title %}

{% block content %}
<div class="popup-overlay" style="display: none;"></div>
<header id="header">
  <div id="brand">
    <a class="brand-link" href="/accounts/"><span class="name-menu">BoardDirector</span></a>
  </div>
  <div id="company">
    {% if current_membership.account.logo %}
      <img src="{{ current_membership.account.logo.url }}" id="logo-img">
    {% endif %}
    {% if request.session.current_account %}
      <a href="{% acc_url 'dashboard:dashboard' %}" class="logo-a">{{ request.session.current_account.name }}</a>
      {% if request.session.current_account.show_guide and current_membership.is_admin %}
        <a href="{% acc_url 'dashboard:getting_started' %}" class="top-close-guide">
          <span class="large">GETTING STARTED GUIDE</span>
          <span class="small">STARTING GUIDE</span>
        </a>
      {% endif %}
    {% endif %}
  </div>

  <div class="holder">
    <ul>
      {% if current_membership %}
        <li>
          <div class="current-membership-photo">
            <img src="{{ current_membership|avatar:'50' }}">
          </div>
        </li>
      {% endif %}
      <li>
        <div class="personal">
          <a class="opener" href="#">{{ current_membership.get_full_name }}</a>
          <div class="drop">
            <ul>
              {% if current_membership %}
                <li><a href="{% url 'profiles:detail' %}">{% trans "My Profile" %}</a></li>
                <li><a href="{% url 'accounts:boards' %}">{% trans "My Boards" %}</a></li>
              {% endif %}
              <li><a class="signout" href="{% url 'auth_logout' %}">({% trans "Sign Out" %})</a></li>
            </ul>
          </div>
        </div>
      </li>
      {% if current_membership.is_admin %}
        <li>
          <div class="settings">
            <a class="opener" href="#">{% trans "Settings" %}</a>
            <div class="drop">
              <ul>
                <li><a class="account-settings" href="{% acc_url 'board_detail' %}">{% trans "Board Settings" %}</a></li>
                <li><a class="account-users" href="{% acc_url 'board_members' %}">{% trans "Members" %}</a></li>
                <li><a class="billing" href="{% url 'billing:update_settings' %}">{% trans "Billing" %}</a></li>
                <li><a class="plans-pricing" href="{% url 'billing:change_plan' %}">{% trans "Plans & Pricing" %}</a></li>
              </ul>
            </div>
          </div>
        </li>
      {% endif %}
    </ul>
  </div>
</header>
<div id="twocolumns">
  {% if request.session.current_account %}
    {% include 'menu.html' %}
  {% endif %}
  <div id="content" class="{% block article_class %}{% endblock article_class %}">
    {% block user_messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="message {% if message.tags %}{{ message.tags }}{% endif %}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock user_messages %}
    {% block workspace %}{% endblock workspace %}
  </div>
</div>
{% endblock content %}